### ISSUE TITLE
Expected download speed?

### ISSUE THREAD

**Issue by nic547** [Aldaviva/RaspberryPiDotnetRepository#2]
Thank you very much for setting this up - this makes for a much nicer experience than manually installing the packages. 

I've downloaded the aspnetcore-runtime for arm64 bullseye and noticed that downloading the packages was rather slow
(apt reports: `Fetched 40.1 MB in 1min 41s (398 kB/s)` on my Pi 4). Same when downloading the packages directly from other systems as well, but not when downloading packages from the official repos,

I usually see speeds in the tens of megabytes per second for the offical debian repos and so I wanted to ask if there's some known limitation with your repository..

**Comment by Aldaviva** [comment]
Hi @nic547, thanks for reporting this.

From Speedtest connection speed tests, I am seeing upload speeds of 21-23 megabits per second, equal to 2.5-2.8 megabytes per second. Not the fastest in the world, but certainly higher than 398 kilobytes per second. I will try some downloads of these packages from other locations to see if I can find any issues.

Thanks.

**Comment by Aldaviva** [comment]
The LAN baseline is 10.8 MB/s which includes the HTTPS server, SSD, local switching & routing, and RPi NIC and microSD speeds.

Over the top, downloads to an AWS EC2 VM (US east coast) were much slower at 1.2 MB/s, closer to what you were seeing. Since this is a lot slower than the 2.6 MB/s connection upload speed, my leading suspicion is ISP peering.

**Comment by nic547** [comment]
Forgot to mention, I'm located in Switzerland, you seem to be located in the US, so the speed might be the result of some weird routing or other ISP shenanigans.

**Comment by Aldaviva** [comment]
Got it, thank you for clarifying. My server is in the US (west coast). I would need a CDN for faster speeds, especially for connections outside of North America.

**Comment by Aldaviva** [comment]
Closing issue for now, but leaving open the possibility of buying CDN service for this repository in the future.

**Comment by Aldaviva** [comment]
I bought CDN service from Azure to front this APT repository. I see that [Microsoft's CDN has two Point of Presence servers in Zurich](https://learn.microsoft.com/en-us/azure/cdn/cdn-pop-locations?toc=%2Fazure%2Ffrontdoor%2FTOC.json#microsoft), so you should see much higher speeds (after the cache is warmed up, see Performance below).

The readme instructions have been updated to point to the new repository URL, `https://raspbian.aldaviva.com`.

## Migration instructions for existing users
If you already added this APT repository to your Raspberry Pi before 2024-04-01, update your APT sources list to point to the new CDN.

If you skip this step, the old URL you're already using will still redirect to the CDN anyway, but there will be a little more latency than if you make this change to use the CDN directly without waiting for those redirections.

1. Open `/etc/apt/sources.list.d/aldaviva.list` with your favorite text editor
2. Replace the URL with `https://raspbian.aldaviva.com/`, for example on bullseye you would change:
    ```diff
    - deb https://west.aldaviva.com/raspbian/ bullseye main
    + deb https://raspbian.aldaviva.com/ bullseye main
    ```
3. Save the `aldaviva.list` file
4. Run `sudo apt update`

Alternatively, you can re-run all of the commands in [Installation > Add APT repository](https://github.com/Aldaviva/RaspberryPiDotnetRepository?tab=readme-ov-file#add-apt-repository) and you should be all set.

## Performance
The Microsoft CDN (Classic) can't be prepopulated without extra complexity and cost, so the first request by anyone to a given file will be a cache miss and just as slow as before, but subsequent requests to that same file after the first time will be much faster.

### Installing ASP.NET Core Runtime bookworm armhf on Pi 3 using CDN (40.0 MByte)

|Attempt|Cache state|Download time|Download speed|
|-:|-|-:|-:|
|1|miss|24 sec|1,658 kByte/sec|
|2|hit|6 sec|6,822 kByte/sec|

## Remaining work
To ensure that users always get up-to-date packages and metadata, I would like to make my repository generator tool automatically purge the CDN cache when a new .NET version is released and the repository is regenerated. This way, users won't have to wait or get error messages when updating to new .NET versions if the CDN would still be returning old content when we already know new content is available from the origin server.

### Resources
- [.NET Azure.ResourceManager.Cdn package](https://www.nuget.org/packages/Azure.ResourceManager.Cdn/)
- [.NET Azure.ResourceManager.Cdn package's CdnEndpointResource.PurgeContentAsync method](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.cdn.cdnendpointresource.purgecontentasync?view=azure-dotnet)
- [REST CDN Endpoint Purge Content request](https://learn.microsoft.com/en-us/rest/api/cdn/endpoints/purge-content?view=rest-cdn-2023-05-01&tabs=HTTP)
- [ResourceManager quickstart tutorial](https://github.com/Azure/azure-sdk-for-net/blob/main/doc/dev/mgmt_quickstart.md)
- [ResourceManager sample app](https://github.com/Azure-Samples/azure-samples-net-management/tree/master/samples/resources/manage-resource)
- [Get started with the Azure CDN Library for .NET](https://learn.microsoft.com/en-us/azure/cdn/cdn-app-dev-net)

**Comment by Aldaviva** [comment]
Finished integrating package generation with CDN caching:
- don't regenerate packages that already exist, to keep their Last-Modified and Etag header values and increase valid cache hits
    - extract control text from existing .deb files
- delete outdated packages so disk usage doesn't grow without bound (was already happening, but needed to be reimplemented due to the first change)
- use Azure ResourceManager API to purge CDN cache of metadata (dists InRelease, Packages.gz, etc) files when any were regenerated

As part of this change, I realized that the .deb AR files were being generated in GNU mode, when they [should have used Common mode](https://en.wikipedia.org/wiki/Ar_(Unix)#File_format_details). I have changed to Common mode to correct this.

**Comment by Aldaviva** [comment]
The updated repository generator successfully created new packages, deleted old packages, updated metadata files, and purged the CDN cache after the 2024-04-09 .NET 8.0.4 release.

Successfully verified that 3 Raspberry Pis with a mix of CPUs and OS versions could upgrade their existing .NET installations to the new version and run .NET apps.
